### ISSUE TITLE
Cant Compile 

### ISSUE THREAD

**Issue by cccdemon** [AlexZzz/libvirt-exporter#11]
build_static.sh fails with:
```
...
make[2]: Leaving directory '/tmp/libvirt-3.8.0/examples'
make[1]: Leaving directory '/tmp/libvirt-3.8.0/examples'
+ sed -i 's/^Libs:.*/& -lnl -ltirpc -lxml2/' /usr/local/lib/pkgconfig/libvirt.pc
+ cd /libvirt-exporter
+ export 'GOPATH=/gopath'
+ go get -d ./...
+ go build --ldflags '-extldflags "-static"' -o libvirt-exporter
# github.com/prometheus/client_golang/prometheus
/gopath/src/github.com/prometheus/client_golang/prometheus/go_collector.go:388:15: undefined: debug.ReadBuildInfo```

**Comment by AlexZzz** [comment]
Hmm, it looks like we don't use go modules there, just using go get. To use go mod we have to update the version of the alpine container to update go version. But, in some modern versions of go we faced with memory leaks in libvirt-exporter, which is triggered somehow by static linkage.

I'll take a closer look on it a bit later.

**Comment by cccdemon** [comment]
> Hmm, it looks like we don't use go modules there, just using go get. To use go mod we have to update the version of the alpine container to update go version. But, in some modern versions of go we faced with memory leaks in libvirt-exporter, which is triggered somehow by static linkage.
> 
> I'll take a closer look on it a bit later.

Yes the memory leak is what we also observed in the past with the rumanzo Exporter. i was not able to figure out why this happens. 

thx for your help :)

**Comment by AlexZzz** [comment]
That's an annoying issue. I think i'm going to change the way it builds and use dynamic linking. The code needs to support ERR_NO_SUPPORT errors, according to the [documentation](https://pkg.go.dev/github.com/libvirt/libvirt-go).

**Comment by cccdemon** [comment]
in my clone i`ve added - well i tried - the steal time metrics (cat /proc/<pid>/shedstat), but before i wanted to try to compile your sources at first. 
Also added an limits.conf to our systemd service to prevent sucking up all memory after 10 hours :D 

I am not a good developer :/ sorry 4 smalltalking.

**Comment by AlexZzz** [comment]
@cccdemon the steal time metric has been recently added to [libvirt api](https://gitlab.com/libvirt/libvirt/-/commit/4719ec15e97d96befaaeecc7bd5c7bcdce53e53d), i'm gonna add it to libvirt-go and use in libvirt-exporter. Looks more native.
