### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by gorSign** [AlexZzz/libvirt-exporter#14]
Want to make libvirt-exporter docker image, command: "docker build -t prometheus-libvirt-exporter -f Dockerbuildimage ."

I use Ubuntu18.04 on HP server where prometheus, prometheus alert manager and other exporters (everything in docker containers) and multiple VMs are running.

Is it mandatory static linking of libvirt library? Or Im doing something in wrong dirrection?

The error is:
rm util/virkeyname-linux.pod util/virkeycode-rfb.pod util/virkeyname-osx.pod util/virkeycode-linux.pod util/virkeycode-osx.pod util/virkeycode-usb.pod util/virkeycode-xt.pod util/virkeycode-win32.pod util/virkeycode-atset3.pod util/virkeycode-atset1.pod util/virkeycode-atset2.pod util/virkeycode-xtkbd.pod util/virkeyname-win32.pod
make[3]: Leaving directory '/tmp/libvirt-3.8.0/src'
make[2]: *** [Makefile:5808: all] Error 2
make[2]: Leaving directory '/tmp/libvirt-3.8.0/src'
make[1]: *** [Makefile:2116: all-recursive] Error 1
make[1]: Leaving directory '/tmp/libvirt-3.8.0'
make: *** [Makefile:2009: all] Error 2
The command '/bin/sh -c ./configure --disable-shared --enable-static --localstatedir=/var --without-storage-mpath &&     make -j$(nproc) &&     make install &&     sed -i 's/^Libs:.*/& -lnl -ltirpc -lxml2/' /usr/local/lib/pkgconfig/libvirt.pc' returned a non-zero code: 2

Could attach whole log if needed.

**Comment by gorSign** [comment]
Already changed "python python-dev" to "python2 python2-dev" in Dockerbuildimage, because of:
ERROR: unable to select packages:
  python (no such package):
    required by: world[python]
  python-dev (no such package):
    required by: world[python-dev]

**Comment by AlexZzz** [comment]
Could you check fix_dockerimage branch? The error is fixed there for me.

**Comment by gorSign** [comment]
Took only Dockerbuildimage from mentioned branch and got:
Step 11/12 : COPY libvirt-patches libvirt-patches
COPY failed: stat /var/lib/docker/tmp/docker-builder690939264/libvirt-patches: no such file or directory


Seems like problem with paths, it is correct location:
ls -l /var/lib/docker/overlay2/900d72e3c5f1bc356230b2a792c052407f881a588a919a19ae125bbec995e6db/diff/gopath/src/github.com/AlexZzz/libvirt-exporter/libvirt-patches
total 4
-rw-r--r-- 1 root root 826 Mar 22 11:10 0001-musl.patch

**Comment by gorSign** [comment]
Could you please share your build/run procedure step-by-step for docker image? 
At me (only) "build_static.sh" creates libvirt-patches, but running Dockerbuildimage can not COPY libvirt-patches.

**Comment by AlexZzz** [comment]
We don't use libvirt-exporter in docker. But we (used to) build it the same way as a build_static.sh works.

I'm currently working on a dynamically linked builds. You may check this [PR](https://github.com/AlexZzz/libvirt-exporter/pull/16). It has Dockerfile to build docker image with libvirt-exporter. Or you may use `build-with` script with Dockerfiles from `build_containers/` to build dynamically linked binary, or use them as an example for your distro/CI.

**Comment by gorSign** [comment]
Thanks a lot for latest release, I have tried it but have a problem with running container...

I took ver 2.0.0, run "build-with ./build_container/Dockerfile.ubuntu1804", docker image is prepared:
libvirtexporterbuild                                                                               latest              1e04cb9dcaed        About an hour ago   891MB

but "docker ps -a" shows it was exited:
CONTAINER ID        IMAGE                                                                                                    COMMAND                  CREATED             STATUS                         PORTS               NAMES
2aa5c59c7927        libvirtexporterbuild                                                                                     "/bin/bash"              39 minutes ago      Exited (0) 37 minutes ago                          optimistic_curran

If I run it by hand "docker run --name prometheus_libvirt -p 9177:9177 -v /var/run/libvirt:/var/run/libvirt libvirtexporterbuild", the same situation:
CONTAINER ID        IMAGE                                                                                                    COMMAND                  CREATED             STATUS                         PORTS               NAMES
51f146314954        libvirtexporterbuild                                                                                     "/bin/bash"              8 seconds ago       Exited (0) 6 seconds ago                           prometheus_libvirt

And empty logs:
root@node1:~libvirt-exporter-2.0.0#docker logs -t prometheus_libvirt
root@node1:~libvirt-exporter-2.0.0#

Any suggestion, hint what is missing?

**Comment by AlexZzz** [comment]
> Any suggestion, hint what is missing?

If you want to build a docker-container with libvirt-exporter as entrypoint, then you should try something like:
1.`docker build -t libvirt-exporter:latest ./` -- it will build a container with libvirt-exporter inside. It is based on the Dockerfile in the root directory of the repo.
2.`docker container run -p9177:9177 -v /var/run/libvirt:/var/run/libvirt libvirt-exporter:latest` - this will run the container.

If you want to have a dynamically linked binary file for ubuntu 18.04, then use `build-with ./build_container/Dockerfile.ubuntu1804`. It will make a build container, which is temporary and needed only to build the binary with right libraries versions. It will build libvirt-exporter binary in that container and leave the binary in ./

Seems like I still need to fix readme:)

**Comment by gorSign** [comment]
Спасибо, всё работает. Когда приеду - с меня пиво ,)
Можно закрыть issue
