### ISSUE TITLE
[BUG] error message an no metrics with blkiotune

### ISSUE THREAD

**Issue by cccdemon** [AlexZzz/libvirt-exporter#18]
**Describe the bug**
` 2021/04/08 05:53:38 Failed to scrape metrics: virError(Code=1, Domain=10, Message='internal error: block_io_throttle inserted entry was not in expected format') ` 

**To Reproduce**
1. Go to your node, start exporter 
`2021/04/08 05:53:38 Failed to scrape metrics: virError(Code=1, Domain=10, Message='internal error: block_io_throttle inserted entry was not in expected format')
`

**Expected behavior**
`# HELP libvirt_domain_block_stats_size_iops_bytes The size of IO operations per second permitted through a block device
# TYPE libvirt_domain_block_stats_size_iops_bytes gauge
libvirt_domain_block_stats_size_iops_bytes{domain="dc533c58-8902-4db6-933b-e626721a5221",target_device="hda"} 0`
**Additional context**
libvirt prozess startet with: 

`/usr/bin/kvm -name guest=UUID,process=qemu:UUIS,debug-threads=on -S -object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-49-dc533c58-8902-4db6-9/master-key.aes -machine pc-i440fx-2.4,accel=kvm,usb=off,dump-guest-core=off,memory-backend=pc.ram -cpu Haswell-noTSX,ss=on,pdpe1gb=on,abm=on -m 8192 -object memory-backend-ram,id=pc.ram,size=8589934592 -overcommit mem-lock=off -smp 8,maxcpus=64,sockets=64,cores=1,threads=1 -uuid UUID -smbios type=0,vendor=unspecified,version=1.0,date=10/09/2015,release=166.0 -smbios type=1,manufacturer=unspecified,product=Legacy Virtual Machine,version=1.0,serial=0123456789,uuid=UUID  -smbios type=2,manufacturer=unspecified,product=Legacy Virtual Machine,version=1.0,serial=0123456789 -no-user-config -nodefaults -chardev socket,id=charmonitor,fd=98,server=on,wait=off -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc -no-shutdown -boot strict=on -device piix3-usb-uhci,id=usb,bus=pci.0,addr=0x1.0x2 -blockdev {"driver":"rbd","pool":"rbd","image":"CEPH-UUID","server":[{"host":"mon1","port":"6789"},{"host":"mon2","port":"6789"},{"host":"mon3","port":"6789"}],"node-name":"libvirt-2-storage","cache":{"direct":false,"no-flush":false},"auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-2-format","read-only":false,"discard":"unmap","cache":{"direct":false,"no-flush":false},"driver":"raw","file":"libvirt-2-storage"} -device ide-hd,bus=ide.0,unit=0,drive=libvirt-2-format,id=ide0-0-0,bootindex=7,write-cache=on -blockdev {"driver":"rbd","pool":"isos","image":"ISO-UUID","server":[{"host":"mon1","port":"6789"},{"host":"mon2","port":"6789"},{"host":"mon3","port":"6789"}],"node-name":"libvirt-1-storage","auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-1-format","read-only":true,"driver":"raw","file":"libvirt-1-storage"} -device ide-cd,bus=ide.1,unit=1,drive=libvirt-1-format,id=ide0-1-1,bootindex=5 -netdev tap,fd=104,id=hostnet0 -device e1000,netdev=hostnet0,id=net0,mac=02:39:3e:56:fa:01,bus=pci.0,addr=0x10,romfile= -device usb-tablet,id=input0,bus=usb.0,port=1 -vnc [::0]:37 -device VGA,id=video0,vgamem_mb=16,bus=pci.0,addr=0x2 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x3 -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny -msg timestamp=on`

**Comment by AlexZzz** [comment]
You've probably built the code from this PR https://github.com/AlexZzz/libvirt-exporter/pull/17.

This error shouldn't appear now anyway.

**Comment by AlexZzz** [comment]
I'll close this bug as It's not reproducible now.
If it appears with the latest release, please reopen.
