### ISSUE TITLE
[FEATURE] stealtime metrics :) 

### ISSUE THREAD

**Issue by cccdemon** [AlexZzz/libvirt-exporter#19]
**Is your feature request related to a problem? Please describe.**
A very powerfull metrics would be the stealttime of a vm, for balancing the while VMs between Servers.

**Describe the solution you'd like**
High Stealtime leads to a low performance of the vm (20% ST means only 80% of CPU is available, and to maximize the hardwareusage this is a powerfull metric)

**Describe alternatives you've considered**
Load of the libvirt Compute Node is not powerfull enough.

**Comment by AlexZzz** [comment]
Yep, would be done as soon as I deal with the libvirt-go go.mod-related [issue](https://gitlab.com/libvirt/libvirt-go/-/issues/7).

It will work with libvirt since v7.2.

**Comment by AlexZzz** [comment]
Feature in master.
