### ISSUE TITLE
Use specific version of docker image instead of latest version

### ISSUE THREAD

**Issue by devrandom0** [AlexZzz/libvirt-exporter#26]
Dear guys

In the [Dockerfile](https://github.com/sinamoghaddas/libvirt-exporter/blob/master/Dockerfile), It doesn't have a specific version; I think it's not good practice for Dockerfile.
Also, in the Dockerfile, it uses the go image, and again it adds (upgrades) the go; It's better to change the docker image instead of it.

I created [this PR](https://github.com/AlexZzz/libvirt-exporter/pull/27) based on my points.

**Comment by AlexZzz** [comment]
Hi!
Thanks for the contribution.
Don't see any problems, merged!
