### ISSUE TITLE
[FEATURE] Disk usage statistics

### ISSUE THREAD

**Issue by gorSign** [AlexZzz/libvirt-exporter#42]
Is it possible to support disk usage on virtual instance? Like it is visible size of disk:
libvirt_domain_block_stats_capacity_bytes{domain="instance-00000222",target_device="sda"}
and it will be useful have also used_bytes.

Thanks a lot!

**Comment by AlexZzz** [comment]
Unfortunately, it's not possible. If you're talking about disk usage as `df` command output, then it is not a disk usage. It is a filesystem usage, and it's not visible from the outside of a vm.
We're able to add any metric of what you see in `virsh` command output.

**Comment by gorSign** [comment]
Yes I see.
Is it somehow possible with usage of virt-df command? It shows df output for vms

**Comment by AlexZzz** [comment]
Yep, it works, but it uses [libguestfs](https://libguestfs.org/). I don't know how it actually works, but at first glance it looks like read-only mount a filesystem from a virtual machine disk.

Add such functionality to libvirt-exporter means make it dependent on different tools with different context while still focus on libvirt instances and libvirtd daemon. It also overlaps responsibility zones. What I mean: libvirt-exporter works with libvirt and doesn't care what is going on inside the machines, it's not his job. For me it looks like a job for another tool, actually I don't think `virt-df` is a good thing for production:)

If you are responsible for the operating system inside a virtual machine, then why don't you use node-exporter? If you want dashboards to be integrated with libvirt information (which is a really good way to work with dashboards!), then you can join on `libvirt_domain_info_meta by (instance_name)`. Need some label replacing, but it is a good way:) Is this your case?

If you're not responsible for the VMs itself, then you don't care about filesystem usage.
